version: "2.1"
services:
  wikijs:
    image: lscr.io/linuxserver/wikijs
    container_name: wikijs
    environment:
      - PUID=0        # 如何查看当前用户的PUID和PGID，直接命令行输入id就行
      - PGID=0
      - TZ=Asia/Shanghai
    volumes:
      - ./wikijs/config:/config  # 配置文件映射到本地，数据不会因为Docker停止而丢失
      - ./wikijs/data:/data  # 数据映射到本地，数据不会因为Docker停止而丢失
    #ports:
     # - 8080:3000   # 左边的8080可以自己调整端口号，右边的3000不要改
    restart: unless-stopped

networks:
  default:
    external:
      name: wikijs.io
